[package]
name = "exia"
version = "0.1.0"
edition = "2021"

[dependencies]
# Terminal UI
ratatui = "0.24"
crossterm = "0.27"

# HTTP client for Gemini API
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# File I/O and utilities
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
dirs = "5.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Process execution
tempfile = "3.8"

# Configuration
config = "0.13"
toml = "0.8"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Terminal input handling
tui-input = "0.8"
