# DSA Learning Assistant Configuration Example
# Copy this file to config.toml and customize as needed

[api]
# Google Gemini API Key (required for AI features)
# Get your API key from: https://makersuite.google.com/app/apikey
gemini_api_key = "your_gemini_api_key_here"

[storage]
# Custom data directory (optional, defaults to system data directory)
# data_dir = "/path/to/custom/data/directory"

[ui]
# Terminal UI settings
theme = "dark"
show_line_numbers = true
auto_save = true

[compiler]
# Rust compilation settings
timeout_seconds = 30
optimization_level = "release"

[learning]
# Learning preferences
default_difficulty = "medium"
preferred_topics = ["arrays", "trees", "graphs"]
max_hints_per_question = 3
