[application]

[web.app]

# HTML title tag content
title = "exia"

# include `assets` in web platform
[web.resource]

# Include assets directory
include = ["assets"]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
