service:

  max_request_size_mb: 128

  grpc_port: 6334

  http_port: 6333

  enable_cors: true

storage:

  storage_path: ./qdrant_storage

  performance:

    max_search_threads: 4

  hnsw_index:

    max_indexing_threads: 2

telemetry_disabled: true
